version: "3.11"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: thorflix
    command: ["/Thorflix/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis