"""Added another bad shit

Revision ID: d55dc528e2a6
Revises: 5d7cc896632e
Create Date: 2023-12-17 22:13:28.708189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55dc528e2a6'
down_revision: Union[str, None] = '5d7cc896632e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile_cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_cover')
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
