import enum
#70aa98b208ab

class GenreAnime(enum.Enum):
    Genre1 = "Комедия"
    Genre2 = "Безумие"
    Genre3 = "Боевые искусства"
    Genre4 = "Вампиры"
    Genre5 = "Военное"
    Genre6 = "Гарем"
    Genre7 = "Демоны"
    Genre8 = "Дзёсэй"
    Genre9 = "Драма"
    Genre10 = "Исторический"
    Genre11 = "Космос"
    Genre12 = "Магия"
    Genre13 = "Машины"
    Genre14 = "Меха"
    Genre15 = "Музыка"
    Genre16 = "Повседневность"
    Genre17 = "Приключения"
    Genre18 = "Романтика"
    Genre19 = "Самураи"
    Genre20 = "Сверхъестественное"
    Genre21 = "Сёдзё"
    Genre22 = "Сёнэн"
    Genre23 = "Сёнэн - Aй"
    Genre24 = "Сэйнэн"
    Genre25 = "Триллер"
    Genre26 = "Ужасы"
    Genre27 = "Фантастика"
    Genre28 = "Фэнтези"
    Genre29 = "Школа"
    Genre30 = "Экшен"
    Genre31 = 'Этти'